# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest https://gist.githubusercontent.com/JanMarvin/181f6fc73c2ac95691b846a740c4bf4c/raw/89588f075bc2aa576b4fc265497dbc084a79bd5b/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - set PATH=C:\GTK2-Runtime\bin;%PATH%

before_build:
  cmd: |
          curl -O http://gemmei.ftp.acc.umu.se/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip
          7z x -o"C:\GTK2-Runtime" gtk+-bundle_2.22.1-20101229_win64.zip
          DEL gtk+-bundle_2.22.1-20101229_win64.zip
          ECHO %PATH%


cache:
  - C:\RLibrary

# Adapt as necessary starting from here
environment:
  global:
    WARNINGS_ARE_ERRORS: 1
  matrix:
  - R_VERSION: devel
    R_ARCH: x64

  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: oldrel
    R_ARCH: x64

matrix:
  fast_finish: true


build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
